Name:           ros-hydro-naoqi-driver
Version:        0.4.1
Release:        0%{?dist}
Summary:        ROS naoqi_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/nao_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-diagnostic-aggregator
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-humanoid-nav-msgs
Requires:       ros-hydro-naoqi-msgs
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-roslaunch
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
BuildRequires:  boost-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-aggregator
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-naoqi-msgs
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-tf
Obsoletes:      ros-hydro-nao-driver

%description
Driver package for the Naoqi robot, providing access to walking commands, joint
angles, and sensor data (odometry, IMU, ...). The most-current version is
compatible with the Nao API version 1.12 or newer, connecting to a real or
simulated Nao by wrapping Aldebaran Robotics' NaoQI API in Python. This requires
the &quot;lib&quot; directory of the Aldebaran Python SDK to be in your
PYTHONPATH environment variable. Note that cameras drivers are provided in a
separate package (naoqi_sensors).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Nov 13 2014 Severin Lemaignan <severin.lemaignan@epfl.ch> - 0.4.1-0
- Autogenerated by Bloom

* Thu Nov 06 2014 Severin Lemaignan <severin.lemaignan@epfl.ch> - 0.4.0-0
- Autogenerated by Bloom

